VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "CChangeItem"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public kind As String
Public assetNo As String
Public Category As String
Public UnitName As String
Public Quantity As Variant
Public Cost As Variant
Public Years As Variant
Public Salvage As Variant
Public monthly As Variant
Public PurchaseDate As Variant
Public Location As String
Public Department As String
Public Note As String
Public RowNo As Long
