VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "CResultRow"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public assetNo As String
Public prevNet As Variant
Public dep As Variant
Public Net As Variant
Public ChangeDesc As String
Public CheckMsg As String
Public Severity As Long
